"""Auto-generated compensating-control CDK snippets -- phase-07 §4 Step 5.

Each function returns a standalone, `cdk deploy`-able Python CDK snippet
string. Output paths (`SentinelReports/f6/{year}-W{week}/controls/
{action_slug}.py`) are the report Lambda's concern (`tools/f6/report.py`),
not this module's -- this module is pure string templating, no S3/CDK
synth calls, so it is trivially unit-testable without moto.
"""

from __future__ import annotations

from iam_sentinel_agents.contracts.shadow_guard import CompensatingControl

_EVENTBRIDGE_TEMPLATE = '''"""Auto-generated by IAM Sentinel F6 Shadow Guard -- compensating control
for {action}. Deploy with `cdk deploy` against the management account.
"""
from aws_cdk import Stack, aws_events as events, aws_events_targets as targets, aws_lambda as lambda_, aws_sns as sns
from constructs import Construct


class {class_name}Stack(Stack):
    def __init__(self, scope: Construct, construct_id: str, *, alert_topic: sns.ITopic, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        alert_fn = lambda_.Function(
            self,
            "AlertFunction",
            runtime=lambda_.Runtime.PYTHON_3_12,
            architecture=lambda_.Architecture.ARM_64,
            handler="index.handler",
            code=lambda_.Code.from_inline(
                "import boto3, json\\n"
                "def handler(event, context):\\n"
                "    boto3.client('sns').publish(\\n"
                "        TopicArn='{{}}'.format(event['topic_arn']),\\n"
                "        Subject='Shadow Guard: {action} observed in mgmt account',\\n"
                "        Message=json.dumps(event),\\n"
                "    )\\n"
            ),
        )
        alert_topic.grant_publish(alert_fn)

        rule = events.Rule(
            self,
            "{class_name}Rule",
            event_pattern=events.EventPattern(
                source=["aws.{service}"],
                detail={{"eventName": ["{event_name}"]}},
            ),
        )
        rule.add_target(targets.LambdaFunction(alert_fn))
'''

_CONFIG_RULE_TEMPLATE = '''"""Auto-generated by IAM Sentinel F6 Shadow Guard -- slow-loop drift
detection for {action}. Deploy with `cdk deploy` against the management
account.
"""
from aws_cdk import Stack, aws_config as config
from constructs import Construct


class {class_name}ConfigRuleStack(Stack):
    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        config.ManagedRule(
            self,
            "{class_name}DriftRule",
            identifier=config.ManagedRuleIdentifiers.CLOUDTRAIL_ENABLED,
            description="Shadow Guard drift check for {action} -- see SentinelReports/f6.",
        )
'''


def _action_slug(action: str) -> str:
    return action.replace(":", "_").replace("-", "_").replace(".", "_").lower()


def _class_name(action: str) -> str:
    return "".join(part.capitalize() for part in _action_slug(action).split("_"))


def eventbridge_rule_snippet(action: str) -> str:
    service, _, event_name = action.partition(":")
    return _EVENTBRIDGE_TEMPLATE.format(
        action=action,
        class_name=_class_name(action),
        service=service,
        event_name=event_name,
    )


def config_rule_snippet(action: str) -> str:
    return _CONFIG_RULE_TEMPLATE.format(action=action, class_name=_class_name(action))


def compensating_control_for_action(
    action: str, *, call_count: int, control_kind: str = "EventBridgeRule"
) -> CompensatingControl:
    if control_kind == "ConfigRule":
        return CompensatingControl(
            for_action=action,
            control_kind="ConfigRule",
            cdk_snippet=config_rule_snippet(action),
            rationale=(
                f"{action} was observed {call_count} time(s) in the management "
                "account, where SCPs never apply -- this Config rule provides "
                "slow-loop drift detection as a compensating control."
            ),
        )
    return CompensatingControl(
        for_action=action,
        control_kind="EventBridgeRule",
        cdk_snippet=eventbridge_rule_snippet(action),
        rationale=(
            f"{action} was observed {call_count} time(s) in the management "
            "account and would be denied by SCP in any member account -- "
            "this EventBridge rule sends an immediate SNS alert as a "
            "compensating control until the underlying access pattern is "
            "remediated at the principal level."
        ),
    )


def output_key_for_action(action: str, *, year: int, week: int) -> str:
    return f"f6/{year}-W{week:02d}/controls/{_action_slug(action)}.py"
