import type { ExecutionMetrics } from '@/types/stream';

export function ExecutionMetricsBar({ metrics }: { metrics: ExecutionMetrics }): JSX.Element {
  const progress = Math.min(100, (metrics.iteration / metrics.maxIterations) * 100);
  const risk = Math.min(100, Math.max(0, metrics.blastRadiusScore * 100));
  const zelkovaIsPass = metrics.zelkovaStatus === 'PASS';
  const zelkovaIsFail = metrics.zelkovaStatus === 'FAIL_PRIVILEGE_ESCALATION';
  return <section aria-label="Live execution metrics" className="sticky top-0 z-10 grid gap-3 rounded-xl border border-zinc-800/80 bg-zinc-900/85 p-4 backdrop-blur-md sm:grid-cols-2 xl:grid-cols-5"><div className="flex items-center gap-3"><svg className="h-11 w-11 -rotate-90"><circle cx="22" cy="22" r="17" fill="none" stroke="currentColor" strokeWidth="4" className="text-zinc-700" /><circle cx="22" cy="22" r="17" fill="none" stroke="currentColor" strokeWidth="4" strokeDasharray="107" strokeDashoffset={107 - (107 * progress) / 100} className={zelkovaIsFail ? 'text-rose-400' : zelkovaIsPass ? 'text-emerald-400' : 'text-cyan-400'} /></svg><div><p className="text-xs text-zinc-500">Debate loop</p><p className="font-semibold text-zinc-100">Turn {metrics.iteration} / {metrics.maxIterations}</p></div></div><Metric label="Token burn" value={`${metrics.tokenBurnRate.toLocaleString()}/min`} /><div><p className="text-xs text-zinc-500">Quota compression</p><p className="font-semibold text-zinc-100">{metrics.policyBytes.toLocaleString()} / 10,240 B</p><div className="mt-2 h-1.5 overflow-hidden rounded bg-zinc-800"><div className={`h-full rounded-full transition-all ${metrics.policyBytes >= 10240 ? 'bg-rose-500' : metrics.policyBytes > 8000 ? 'bg-amber-400' : 'bg-cyan-400'}`} style={{ width: `${Math.min(100, (metrics.policyBytes / 10240) * 100)}%` }} /></div></div><div><p className="text-xs text-zinc-500">Zelkova proof</p><p className={`mt-1 inline-flex rounded-full border px-2 py-1 text-xs font-semibold ${zelkovaIsPass ? 'border-emerald-500/50 bg-emerald-500/10 text-emerald-300' : zelkovaIsFail ? 'border-rose-500/50 bg-rose-500/10 text-rose-300' : 'border-amber-500/50 bg-amber-500/10 text-amber-300'}`}>{metrics.zelkovaStatus} · {metrics.alertCount} alerts</p></div><div><p className="text-xs text-zinc-500">Blast radius</p><p className={`font-semibold ${risk > 50 ? 'text-rose-300' : risk > 25 ? 'text-amber-300' : 'text-zinc-100'}`}>{risk.toFixed(0)}% risk</p><div className="mt-2 h-2 overflow-hidden rounded bg-gradient-to-r from-emerald-500 via-amber-400 to-rose-500"><div className="h-full bg-zinc-950/75" style={{ marginLeft: `${risk}%` }} /></div></div></section>;
}

function Metric({ label, value }: { label: string; value: string }): JSX.Element { return <div><p className="text-xs text-zinc-500">{label}</p><p className="mt-1 font-semibold text-zinc-100">{value}</p></div>; }
