"""phase-07 §8: "Report: fixture-driven snapshot test on the generated CDK
snippets." Pins the exact generated Python CDK source for a fixed action so
a future template edit that silently breaks `cdk synth` (e.g. a stray
`{{`/`}}` escaping bug, or a renamed construct) fails a test instead of
only surfacing at deploy time -- `cdk synth` itself is deferred per ADR
0031 (no CDK app wiring exists yet for any specialist).
"""

from __future__ import annotations

import pytest

from iam_sentinel_agents.tools.f6.cdk_templates import (
    compensating_control_for_action,
    config_rule_snippet,
    eventbridge_rule_snippet,
    output_key_for_action,
)

pytestmark = pytest.mark.unit

_ACTION = "organizations:deletepolicy"


def test_eventbridge_snippet_snapshot() -> None:
    snippet = eventbridge_rule_snippet(_ACTION)

    assert snippet == (
        '"""Auto-generated by IAM Sentinel F6 Shadow Guard -- compensating control\n'
        "for organizations:deletepolicy. Deploy with `cdk deploy` against the "
        "management account.\n"
        '"""\n'
        "from aws_cdk import Stack, aws_events as events, aws_events_targets as "
        "targets, aws_lambda as lambda_, aws_sns as sns\n"
        "from constructs import Construct\n"
        "\n"
        "\n"
        "class OrganizationsDeletepolicyStack(Stack):\n"
        "    def __init__(self, scope: Construct, construct_id: str, *, "
        "alert_topic: sns.ITopic, **kwargs) -> None:\n"
        "        super().__init__(scope, construct_id, **kwargs)\n"
        "\n"
        "        alert_fn = lambda_.Function(\n"
        "            self,\n"
        '            "AlertFunction",\n'
        "            runtime=lambda_.Runtime.PYTHON_3_12,\n"
        "            architecture=lambda_.Architecture.ARM_64,\n"
        '            handler="index.handler",\n'
        "            code=lambda_.Code.from_inline(\n"
        '                "import boto3, json\\n"\n'
        '                "def handler(event, context):\\n"\n'
        "                \"    boto3.client('sns').publish(\\n\"\n"
        "                \"        TopicArn='{}'.format(event['topic_arn']),\\n\"\n"
        "                \"        Subject='Shadow Guard: organizations:deletepolicy "
        "observed in mgmt account',\\n\"\n"
        '                "        Message=json.dumps(event),\\n"\n'
        "                \"    )\\n\"\n"
        "            ),\n"
        "        )\n"
        "        alert_topic.grant_publish(alert_fn)\n"
        "\n"
        "        rule = events.Rule(\n"
        "            self,\n"
        '            "OrganizationsDeletepolicyRule",\n'
        "            event_pattern=events.EventPattern(\n"
        '                source=["aws.organizations"],\n'
        '                detail={"eventName": ["deletepolicy"]},\n'
        "            ),\n"
        "        )\n"
        "        rule.add_target(targets.LambdaFunction(alert_fn))\n"
    )


def test_config_rule_snippet_snapshot() -> None:
    snippet = config_rule_snippet(_ACTION)

    assert snippet == (
        '"""Auto-generated by IAM Sentinel F6 Shadow Guard -- slow-loop drift\n'
        "detection for organizations:deletepolicy. Deploy with `cdk deploy` "
        "against the management\n"
        'account.\n"""\n'
        "from aws_cdk import Stack, aws_config as config\n"
        "from constructs import Construct\n"
        "\n"
        "\n"
        "class OrganizationsDeletepolicyConfigRuleStack(Stack):\n"
        "    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> "
        "None:\n"
        "        super().__init__(scope, construct_id, **kwargs)\n"
        "\n"
        "        config.ManagedRule(\n"
        "            self,\n"
        '            "OrganizationsDeletepolicyDriftRule",\n'
        "            identifier=config.ManagedRuleIdentifiers.CLOUDTRAIL_ENABLED,\n"
        '            description="Shadow Guard drift check for '
        'organizations:deletepolicy -- see SentinelReports/f6.",\n'
        "        )\n"
    )


def test_snippet_is_syntactically_valid_python() -> None:
    """Cheapest possible stand-in for a real `cdk synth` (deferred, ADR
    0031): every generated snippet must at least parse as Python."""
    compile(eventbridge_rule_snippet(_ACTION), "<eventbridge_snippet>", "exec")
    compile(config_rule_snippet(_ACTION), "<config_rule_snippet>", "exec")


def test_compensating_control_rationale_cites_the_observed_call_count() -> None:
    control = compensating_control_for_action(_ACTION, call_count=42)

    assert "42 time(s)" in control.rationale
    assert control.for_action == _ACTION


def test_output_key_for_action_matches_the_spec_path_shape() -> None:
    key = output_key_for_action(_ACTION, year=2026, week=31)

    assert key == "f6/2026-W31/controls/organizations_deletepolicy.py"
