/**
 * Hand-typed mirrors of `backend/src/iam_sentinel_backend/schemas/*.py`
 * (`ResponseBase`/`RequestBase` Pydantic models), not machine-generated.
 *
 * `backend/openapi.golden.json` (phase-00's contract-diff artifact) types
 * every route's request body correctly but its response bodies as bare
 * `{}` — every router returns `dict[str, Any]` from `envelope.ok()`
 * (see `backend/src/iam_sentinel_backend/envelope.py`), which is honest
 * FastAPI/Pydantic behavior (the envelope wraps an already-validated
 * model in a plain dict at the route boundary) but gives
 * `openapi-typescript` nothing to generate a response type from. See
 * ADR 0021: rather than change the backend's OpenAPI shape to serve a
 * frontend-only codegen convenience, this file hand-mirrors
 * `schemas/{common,finding,decision,chat,approvals,operations}.py`
 * field-for-field. `lib/api-types.gen.ts` (generated by
 * `openapi-typescript`, see `package.json`'s `generate:api-types`) still
 * owns every REQUEST body type — imported below, not duplicated.
 */
import type { components } from "@/lib/api-types.gen";

export type FeatureId = "F1" | "F2" | "F3" | "F4" | "F5" | "F6" | "F7" | "F8";
export type Severity = "INFO" | "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
export type DecisionStatus = "ANSWERED" | "ESCALATED" | "AUTO_REMEDIATED" | "REJECTED";
export type FaultClass =
  | "transient_throttling"
  | "transient_network"
  | "eventual_consistency"
  | "adapter_fault"
  | "model_fault"
  | "logic_fault"
  | "infra_drift"
  | "data_corruption"
  | "region_outage";

export interface ErrorDetail {
  code: string;
  message: string;
  correlation_id: string;
}

export interface ApiOk<T> {
  ok: true;
  data: T;
}

export interface ApiErr {
  ok: false;
  error: ErrorDetail;
}

export type ApiEnvelope<T> = ApiOk<T> | ApiErr;

export interface AwsDocCitationOut {
  gap_id: FeatureId;
  quote: string;
  source: string;
  url: string;
  retrieved_on: string;
}

export interface FindingOut {
  finding_id: string;
  feature_id: FeatureId;
  account_id: string;
  principal_arn: string | null;
  resource_arn: string | null;
  severity: Severity;
  title: string;
  detail: string;
  aws_doc_citation: AwsDocCitationOut;
  payload: Record<string, unknown>;
  detected_at: string;
  expires_at: string | null;
  evidence_ref: Record<string, unknown> | null;
  status: string;
}

export interface FindingsPage {
  items: FindingOut[];
  next_token: string | null;
}

/**
 * `GET /evidence/{ref}` (backend phase-04) doesn't exist in this codebase
 * yet -- built in parallel on another branch. Shape assumed from
 * `docs/DATA_CONTRACTS.md` §6 `EvidenceRecord` plus a `verified` flag: the
 * browser can never do the KMS/RSA-PSS signature check itself (it doesn't
 * hold the key), so the backend must return the verification result
 * alongside the body, not just the raw signature. Revisit once backend
 * phase-04 lands and publishes its real response schema.
 */
export interface EvidenceOut {
  ref: string;
  kind: "specialist_input" | "specialist_output" | "zelkova_invocation" | "policy_mutation" | "guardrail_intervention";
  correlation_id: string;
  feature_id: FeatureId;
  body: Record<string, unknown>;
  sha256: string;
  verified: boolean;
}

export interface DecisionOut {
  decision_id: string;
  correlation_id: string;
  principal: string;
  query: Record<string, unknown>;
  specialist_verdicts: Record<string, unknown>[];
  findings: FindingOut[];
  remediations_proposed: Record<string, unknown>[];
  remediations_applied: Record<string, unknown>[];
  status: DecisionStatus;
  narrative: string;
  evidence_ref: Record<string, unknown>;
  decided_at: string;
}

export interface DecisionsPage {
  items: DecisionOut[];
  next_token: string | null;
}

export interface ApprovalResponse {
  decision_id: string;
  status: string;
}

export interface FaultRecordOut {
  correlation_id: string;
  fault_class: FaultClass;
  origin: string;
  action_taken: "retried" | "fell_back" | "escalated" | "auto_repaired" | "paged";
  detail: string;
  detected_at: string;
  resolved_at: string | null;
}

export interface FaultsPage {
  items: FaultRecordOut[];
  next_token: string | null;
}

export interface CostReportOut {
  report_key: string;
  body: Record<string, unknown>;
}

export interface HealthResponse {
  stage: string;
  commit: string;
}

// Request bodies come straight from the generated OpenAPI schema — those
// ARE correctly typed by openapi-typescript because FastAPI's `body:
// ChatRequest` parameter annotations produce real `$ref`s, unlike the
// `dict[str, Any]` return types above.
export type ChatRequest = components["schemas"]["ChatRequest"];
export type ApprovalRequest = components["schemas"]["ApprovalRequest"];
